### ISSUE TITLE
no image are showing

### ISSUE THREAD

**Issue by mohammadaziz96** [code-flu/angular-bar-chart-race#1]
can you add a function to add images on the right and left of the bar.

**Comment by code-flu** [comment]
Added Function to Add Images to the Bar Chart

#### Commit ID: [bbe9a6ca8dfa34a575fb13983ee3c78eca6fe99b](https://github.com/code-flu/angular-bar-chart-race/commit/bbe9a6ca8dfa34a575fb13983ee3c78eca6fe99b)

This commit introduces a new feature that allows adding images to the left of the bar in the bar chart. This enhancement provides better visual representation and more customization options for the bar chart.
